### ISSUE TITLE
Cache is not uploaded if cache hit occured but vcpkg rebuilt dependencies anyway

### ISSUE THREAD

**Issue by equeim** [lukka/run-vcpkg#132]
Vcpkg decides whether to use packages based from binary cache based on many factors, including version of C++ compiler or CMake (see https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md#implementation-notes-internal-details-subject-to-change-without-notice). run-vcpkg, however, does not take this into account when computing cache key (and it would be unfeasible to do so), This means that when build environment has changed without change in cache key (e.g. Windows runner was updated and version of CMake changed), all dependencies will be rebuilt from scratch in every workflow run until cache key changes and new cache actually gets uploaded.

I see only one possible soluttion to this problem - always append some random value or `${{ github.sha }}` to cache key so that exact matches don't occur and cache is always uploaded.

**Comment by lukka** [comment]
@equeim in principle the cache key computed by `run-vcpkg` should be changing whenever the GitHub runner image changes, by putting the ImageOs value in the key:

```ts
let firstSegment = `runnerOS=${process.env.ImageOS ? process.env.ImageOS : process.platform}`;
```

Is the first segment of your keys only the platform without the complete version info of the GH runner image?

A doubt I have is that I think `ImageOs` contained the full version of the GH runner image itself, but if it does not, then the computed key needs to be augmented to be changing whenever the GH runner image changes.

Regarding your solution, I think you want to rely on the fallback keys, since if you generate a random key you would never be able to match it in the subsequent runs. If you want to try to add a random (I mean that changes for every workflow run) segment to your key you may leverage the `appendedCacheKey` input. If you try this route, let me know if there are any limits in size of the stord cache, as this would create a new cache at every run of the workflow with a different key.

Anyway I prefer to fix the computation of the key in run-vcpkg so that it changes appropriately, ideas are welcome!

**Comment by lukka** [comment]
@equeim this should be fixed in https://github.com/lukka/run-vcpkg/releases/tag/v10.2. The reason is that the cache key is including the version of the image version of the runners, that is the cache is going to be missed (and created anew) when the image changes as well.
