### ISSUE TITLE
Could not find MSBuild version with C++ support

### ISSUE THREAD

**Issue by micahsnyder** [lukka/run-vcpkg#142]
We started seeing this recently in github actions:
```
Build vcpkg
  tool: C:\Windows\system32\cmd.exe
  Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) needs to be installed.
  At D:\a\clamav\clamav\vcpkg\scripts\bootstrap.ps1:195 char:5
  +     throw "Could not find MSBuild version with C++ support. VS2015, V ...
  +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      + CategoryInfo          : OperationStopped: (Could not find ...o be installed.:String) [], RuntimeException
      + FullyQualifiedErrorId : Could not find MSBuild version with C++ support. VS2015, VS2017, or VS2019 (with C++) ne 
     eds to be installed.
```

We've been using `windows-latest`. (for ref: https://github.com/Cisco-Talos/clamav/blob/main/.github/workflows/cmake.yml#L23-L83)

Do you know if something changed and we need to pick a different runner or something?

**Comment by lukka** [comment]
@micahsnyder the problem is that the `bootstrap.ps1` script of the vcpkg version you use is not able to find `msbuild.exe` in a VS 2022 installation. It tries to search for it on VS installation that reports `14`, `15` or `16` as major version, while VS2022 is major version `17`.

Probably it is best to stick to a precise image OS, i.e. rather than `windows-latest`, which may change at any time: you can pin your workflow to an OS image that contains VS 2019.

**Comment by micahsnyder** [comment]
Thanks @lukka that makes sense. And thanks for the crazy fast response. 

Github must've switched windows-latest to windows-2022 recently. I will roll us back to windows-2019, and upgrade our run-vcpkg to 7.4.  I don't have time this minute to hop up to 10.x yet, but will do that eventually and then revisit using windows-2022 image.
