### ISSUE TITLE
Error running on self-hosted raspberry pi (arm64)

### ISSUE THREAD

**Issue by vadi2** [lukka/run-vcpkg#152]
Looking to setup a build on a self-hosted raspberry pi (arm64) for performance analysis reasons (cloud gives no guarantees on execution consistency) and while the `get-vcpkg` action runs okay, `run-vcpkg` [stumbles](https://github.com/Mudlet/Mudlet/runs/7800720708?check_suite_focus=true): 

```
Build vcpkg
  tool: /usr/bin/sh
  Unable to determine a binary release of vcpkg; attempting to build from source.
  Building vcpkg-tool...
  CMake Error: Could not find CMAKE_ROOT !!!
  CMake has most likely not been installed correctly.
  Modules directory not found in
  /home/mudletpi/actions-runner/_work/_temp/773599641/cmake-3.20.1-linux-x86_64/share/cmake-3.18
  CMake Error: Error executing cmake::LoadCache(). Aborting.
  
  Error: Last command execution failed with error code '1'.
```

It looks to be trying to use `x86_64` when it ought to be using `arm64`.

**Comment by lukka** [comment]
@vadi2 just by looking to the logs there are a couple of things that deserve attention, but I have not spotted exactly what is wrong.
Few things to check:
- is the restored cmake from cache the correct one?  It is located under this subtree `/home/mudletpi/actions-runner/_work/_temp/773599641`, and added to the PATH. Can you check if the executable is for `arm`?
- The failure happening while vcpkg is running is usually due to missing files under `/usr/lib/share`, but it is strange it searches for those in the directory named `cmake-3.18`, which does not match the version 3.20: 
`Modules directory not found in /home/mudletpi/actions-runner/_work/_temp/773599641/cmake-3.20.1-linux-x86_64/share/cmake-3.18`. 

Probably a log with increased verbosity by setting the `ACTIONS_STEP_DEBUG` secret to `true` would provide more diag info.

**Comment by vadi2** [comment]
Gotcha. I went another way for now, not using run-vcpkg, so I'll close the issue to save on time.
