### ISSUE TITLE
Restore key for runner OS updates

### ISSUE THREAD

**Issue by quyykk** [lukka/run-vcpkg#162]
The runner OSs get regular updates, but the updates cause a complete cache miss and cause a complete rebuild for every dependency.

It would be nice if there was a restore key for the update part of the OS. For example, on `windows-latest` where the current `runnerOS` key is `win2220220925.1` having a restore key for `win22`.

**Comment by lukka** [comment]
@quyykk I am conflicted in this regard, more specifically when the cache is created on an OS image rather than another, those two images may or may not differ regarding the generated cached artifact (i.e. the differences do not matter), but they do differ for sure. Hence it is more cautious to assume that the cached artifact needs to be recomputed and saved in the cache again rather than blinding assuming the artifact may be fine. On the other hand, minimizing the number of cache regeneration is also very important. 

Questions:
- what is the cadence of the updates? that is, given a scenario, what is the overall impact? I think this is only valid for GH hosted runners, not the self hosted ones, and it may greatly vary on the users scenarios (that is it may be fine for most but not for all). 
- how to deal with scenario where the cache is not recreated but reused over different OS image, nevertheless this leads to a blocking build failure? Then the user needs to manually work around by enforcing the invalidation of the existing cached artifact.
- could the cache restore key computation strategy be designed  ad-hoc per platform? That is, IIRC only the MacOS platform required the cached artifact to be recomputed at each new image (there was a blocking issue about the cached vcpkg executable), but not Windows nor Linux.

Having answers to the questions above may help in design a solution regarding how the restore key could be computed.

**Comment by quyykk** [comment]
> what is the cadence of the updates?

Pretty regularly from what I can tell. Looking at https://github.com/actions/runner-images/releases they seem to happen weekly (more or less).

> how to deal with scenario where the cache is not recreated but reused over different OS image, nevertheless this leads to a blocking build failure?

I think this would be rarely the case. vcpkg notices if the environment has changed and recompiles the libraries if necessary, so unless the OS image update contains a breaking change, this is safe.

**Comment by quyykk** [comment]
> Then the user needs to manually work around by enforcing the invalidation of the existing cached artifact.

Just thought I'd mention it that GitHub added cache management so manually invalidating the cache is no longer necessary; you can simply delete the problematic cache from the web interface.

**Comment by lukka** [comment]
@quyykk i think this issue could be solved since the addition of GHA to vcpkg, let me know! Thanks for your work!
Solved by this release: https://github.com/lukka/run-vcpkg/releases/tag/v11.0

**Comment by quyykk** [comment]
Thanks! Seems to work perfectly. Is this line in the output intended? https://github.com/quyykk/vcpkg-gha-demo/actions/runs/4575274717/jobs/8077908474#step:3:210

**Comment by quyykk** [comment]
@lukka seems like the action still caches the packages. https://github.com/quyykk/vcpkg-gha-demo/actions/runs/4575831693/jobs/8079175385#step:3:153

**Comment by lukka** [comment]
@quyykk fortunately the run-vcpkg action caches only vcpkg executable and its data file and not packages built by vcpkg.
The output of run-vcpkg


>  Caching paths: '/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/*,!/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/installed,!/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/vcpkg_installed,!/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/packages,!/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/buildtrees,!/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/downloads'


should be read as:

> _Saving_
>
> ```/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/*,```
> 
> _but not any of the following:_
>
> !/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/installed,
> !/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/vcpkg_installed,
> !/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/packages,
> !/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/buildtrees,
> !/home/runner/work/vcpkg-gha-demo/vcpkg-gha-demo/vcpkg/downloads'

I double checked this on the [validation repository](https://github.com/lukka/CppBuildTasks-Validation) as well.

**Comment by quyykk** [comment]
Oh so it caches all the port files as well? That's why it's so big, interesting.

**Comment by lukka** [comment]
@quyykk yes, it caches the ports as well, and it can be disabled with [doNotCache:true](https://github.com/lukka/run-vcpkg/blob/main/action.yml#LL30C3-L30C13). I may also consider removing this caching entirely, as it may be not that relevant anymore, hard to decide :)
