### ISSUE TITLE
Need PATH to be set to included libraries created by vcpkg

### ISSUE THREAD

**Issue by nordlow** [lukka/run-vcpkg#176]
At https://github.com/nordlow/gmp-d/actions/runs/3744997058/jobs/6364953383 my build fails because I'm not using cmake but instead D's default build tool dub. I'm guessing it fails because the PATH is not setup to include the artificats (in my case gmp.lib) that are created by vcpkg. How can I make the happen?

**Comment by lukka** [comment]
@nordlow how the local build is working with vcpkg on Windows? The idea is that whatever you do locally (and works), you should be doing on the workflow, in order to have a perfect reproducible build process.

The `run-vcpkg` action itself does set `VCPKG_ROOT` environment variable, and it is not manipulating the environment variables in any other way. It is up to something else, e.g., the CMake toolchain file or `vcpkg integrate install` command, that are putting in place the integration between the C++ toolchain you use and the vcpkg artifacts.

**Comment by nordlow** [comment]
Ok, thanks. I'm looking at https://vcpkg.readthedocs.io/en/latest/commands/integrate/ and cannot figure out if I can use `vcpkg` to set the path to where my gmp.lib is installed.

**Comment by lukka** [comment]
@nordlow you may look to the output log of the command you launch `vcpkg` with to understand where the `lib` and `include` directories are. For example, if you use the manifest mode (e.g. using a `vcpkg.json` to list the ports to be installed), the built artifacts will be put under `<root>/vcpkg_installed/<triplet>/`, where there should be the `lib` and `include` directories among others. The `<root>` varies, it is for example the "CMake's binary directory" when using cmake with the vcpkg's toolchain file (e.g. when you launch `cmake -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake`.

**Comment by lukka** [comment]
@nordlow let me know if it worked and which solution you found out. Closing this issue now to cleanup old entries.

**Comment by nordlow** [comment]
Sorry, I don't have time to look into this.
