### ISSUE TITLE
run-vcpkg failing with "dyld: Symbol not found: __ZNKSt3_V214error_category10_M_messageB5cxx11Ei"

### ISSUE THREAD

**Issue by mrheffern** [lukka/run-vcpkg#198]
![run-vcpkg fail](https://user-images.githubusercontent.com/8864846/231277447-5abe849b-d347-4b00-9b39-ee977b38cdb9.png)

I know I'm using old stuff. I inherited all of this and it was working perfectly until about 3 weeks ago and now out of the blue it stops working. I even tried it with old commits that had worked successfully in the past yet they are failing now too. To be clear, I'm using run-vcpkg@v5.0.

Is there any reason that this would stop working out of the blue? I would prefer to be able to fix it as it is but I would also be open to upgrading if that is what needed to be done, although I'm not sure what that would entail. I am a new C++ developer and I am still learning the basics of these packages. Please forgive my ignorance and thank you for any help in advance!

**Comment by mrheffern** [comment]
I forgot to mention that this is only happening on a macos-11 runner. My windows runner is working just fine regarding run-vcpkg.

**Comment by lukka** [comment]
@mrheffern thanks for reporting this! I think the issue is that run-vcpkg@v5 did not account for the version of the underlying OS in the computation of the cache key, and the old cached binaries built with previous macOS based image are being reused on a newer image and fail to run (they should be rebuilt instead, but run-vcpkg is not doing that in version 5).

I'd suggest to upgrade to `run-vcpkg@v7` and then it should just be working with the same set of inputs. Or you could use a more recent `run-vcpkg@v11`, but this requires a recent vcpkg version  and also you need to switch to vcpkg's manifest mode (i.e., vcpkg.json).

Take a look at [this C++ project template](https://github.com/lukka/CppCMakeVcpkgTemplate) and you should get it working again.

**Comment by mrheffern** [comment]
Wow! That completely fixed it! I can't fully express how grateful I am to you. Thank you lukka!!! You totally saved me.

 Any reason this would have stopped working in the last 3 weeks specifically, with no changes to my codebase? While I don't fully understand the implications of everything you pointed out, they didn't sound like issues that would have occured in the last three weeks.

Again, thank you lukka!

**Comment by lukka** [comment]
@mrheffern good question, the reason is likely that the binaries built long time ago on an older version of the macOS runner, now cannot run on a more recent macOS runner, and those needs to be rebuilt, which the newer action did automatically.
If it is working, that's good to know, thanks for the kind message! :)
