### ISSUE TITLE
dist/index.js not rebuilt after @actions/core update

### ISSUE THREAD

**Issue by koivunej** [lukka/run-vcpkg#43]
Similar to https://github.com/hecrj/setup-rust-action/issues/23, @actions/core was updated in #42 but using this action still causes deprecation warnings (documented in the linked issue). I tried to `npm install` to `npm run build` but:

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@lukka%2frun-vcpkg-lib - Not found
npm ERR! 404
npm ERR! 404  '@lukka/run-vcpkg-lib@0.14.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'run-vcpkg'
```

**Comment by lukka** [comment]
@koivunej thanks for the report, i'll publish a new action as soon as I can with the updated `@actions/core`.

Also, glad you want to contribute! Probably the error E404 due to the missing of a `.npmrc` file with content:

`registry=https://npm.pkg.github.com/lukka`

Can you please check if the suggestion works?

The missing package is published in this repository [lukka/run-cmake-vcpkg-action-libs](https://github.com/lukka/run-cmake-vcpkg-action-libs), along with others that I have not published on npm yet.

**Comment by koivunej** [comment]
Adding a `.npm` in the working directory with the content you described does not fix the issue, but it becomes a different one:

```
$ npm install
(many warnings omitted)
npm WARN tar ENOENT: no such file or directory, open '$working_copy/node_modules/.staging/lodash-0fb97ddc/fp/zipWith.js'
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="GitHub Package Registry"
```

With some bash-fu all of the `WARN tar ENOENT: no such file or directory, open` packages are:

```
acorn-11c07eaf
acorn-c54bcb18
babel-jest-1d4230b9
@babel/parser-7dfacc71
@jest/core-0199df20
@jest/environment-e489c758
jest-environment-node-874cab6a
jest-jasmine2-14e56598
lodash-0fb97ddc
@octokit/types-0074d35b
@octokit/types-a635a10d
@octokit/types-a79b4e2e
@octokit/types-d231cc14
@octokit/types-d8e9e7e3
ts-jest-ee514e18
@zeit/ncc-516bf0ac
```

In addition this is the only lstat error:

```
npm WARN tar ENOENT: no such file or directory, lstat '$working_copy/node_modules/.staging/ts-jest-ee514e18/dist/cli/helpers'
```

**Comment by koivunej** [comment]
Note I don't really know anything about cause for `npm WARN tar ENOENT: ...` errors are I just wanted to summarize them.

From earlier:
> The missing package is published in this repository lukka/run-cmake-vcpkg-action-libs, along with others that I have not published on npm yet.

This makes sense for a sensible explanation :) If you want me to try out anything else, let me know!

**Comment by lukka** [comment]
@koivunej  looks like that in order to access a public package in GitHub Registry you need a token (aka PAT, Personal Access Token).

Here there is a related one year long discussion:  https://github.community/t/download-from-github-package-registry-without-authentication/14407/63

Perhaps if you add a token to your local .npmrc (but please never put it under source control), it may be working.
The token only needs to be able to read packages (e.g. `read:packages`).

I think I need to document how exactly this works, or just publish packages on npmjs :)

**Comment by koivunej** [comment]
> I think I need to document how exactly this works, or just publish packages on npmjs :)

The latter might be the easier solution :) With the former, I think you are going to continue getting issues like mine as I just see "package.json" and assume I can just use `npm install` and then look for the `npm run build` equivalent.

**Comment by lukka** [comment]
The security fixes are included in https://github.com/lukka/run-vcpkg/releases/tag/v4.1.
This release does not show the warnings anymore, which is the whole point of this issue.
Note: just use as usual the branch `v4` to stay on most recent `v4.x` version, with bug fixes and security fixes.

Publishing the dependencies on NPM has not been done, as that would require more changes than I expected. I hope GitNub, now that owns NPM Registry, can quickly create a seamless experience for consume public GitHub package without requiring authentication.

**Comment by koivunej** [comment]
Thanks, with v4.1 the build is green with zero warnings!
