### ISSUE TITLE
Use provided vcpkg

### ISSUE THREAD

**Issue by Shatur95** [lukka/run-vcpkg#44]
Hi! Is it possible to use already available vcpkg on CI? For example, Windows 2019 [already have](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md#package-management) vcpkg installed.

**Comment by lukka** [comment]
By design it is not possible. 
vcpkg is a Git repository that for each commit id, it contains both the tool and all the libraries it provides. Hence if you want to have total control over your dependencies, you need to pin the commit id of vcpkg that is meant to be used as your project's  dependency. One way to achieve this is to use [vcpkg a submodule of your repository.](https://github.com/lukka/run-vcpkg/blob/main/README.md#use-vcpkg-as-a-submodule-of-your-repository).
 
OTOH if you want to rely on an unknown version of vcpkg preinstalled on the GitHub hosted runners:
- how do you ensure you are using the same commit id locally while building on your dev box?
- your project is forced to use whatever the GitHub hosted runner dictates to use, it can change anytime, breaking the build.

**Comment by Shatur95** [comment]
Got it, thanks!

**Comment by Shatur95** [comment]
BTW, in future versions, it may be possible to [specify package versions](https://github.com/microsoft/vcpkg/pull/11758).
