### ISSUE TITLE
Tag in vcpkgCommitId

### ISSUE THREAD

**Issue by Shatur** [lukka/run-vcpkg#47]
If I understand correctly, then `vcpkgCommitId` cannot contain a tag. But if you specify it, then I will get silently non-working cache. [Workflow output](https://github.com/crow-translate/crow-translate/runs/1249514303?check_suite_focus=true) with tag in `vcpkgCommitId` (the cache is unpacked but not used).

**Comment by Shatur95** [comment]
Is it possible to add tagging support to `vcpkgCommitId`?

**Comment by lukka** [comment]
Please take a look to [run-vcpkg@v10](https://github.com/marketplace/actions/run-vcpkg) and see if suites your needs. Feel free to reopen this or a new ticket about any problem you may see.

**Comment by lukka** [comment]
@Shatur right, tags are not supported. Reopening this item.

**Comment by justusranvier** [comment]
> the best practice is to [use vcpkg as a submodule](https://github.com/lukka/run-vcpkg/blob/main/README.md#use-vcpkg-as-a-submodule-of-your-repository)

I guess you've never run into this issue before, but using vcpkg as a submodule is actually a terrible idea if you need to run vcpkg on windows images because of the MAX_PATH issue.

There are several packages in vcpkg whose build process runs right up to the limit and only work if you use C:\VCPKG. Any base path longer than that and you'll get hard to diagnose failures and confusing error messages that take a long time to track back to their root cause.

**Comment by lukka** [comment]
@justusranvier hitting the `MAX_PATH` limitation is certainly a nightmare that forces unnecessary changes to workaround it. 
The most important thing is to _pin_ a specific version of `vcpkg`, so that the build reliably works in the same way for build executed by the devs and on CI build agent. Pinning using "vcpkg as a submodule" is one way, but certainly there can be others as long as they are stored in the source control. Which other approach would you suggest? A PR to improve the current best practices content is welcome.

There are also other questions as well that would help in narrowing down the problem and probably delineating a solution: 
- what is the extent of the problem of pinning the vcpkg version using a Git submodule? Is it a complete failure in any case, or only surfacing when some port is being used? This best practice is described in the [vcpkg.io](https://vcpkg.io/en/getting-started.html), and problem with it should be highlighted to the vcpkg project as an GH issue.
- are you using  a self hosted agent? I do not have a direct experience about this, but hopefully the Windows hosted agents are setup to not hit the MAX_PATH limitation.

**Comment by justusranvier** [comment]
> * Is it a complete failure in any case, or only surfacing when some port is being used?

Not all ports will result in exceeding MAX_PATH, but qtdeclarative and its dependencies will unless the base path is very short (C:\VCPKG)

> but hopefully the Windows hosted agents are setup to not hit the MAX_PATH limitation

From my experience the hosted runners do hit MAX_PATH. I have read there are registry hacks to turn off this limitation but they require a reboot so there's no way to use them in a hosted runner.

**Comment by lukka** [comment]
Closing as more than one year of inactivity. Feel free to ask to reopen if needed.
