### ISSUE TITLE
Cache miss but fails to cache too

### ISSUE THREAD

**Issue by TrueBrain** [lukka/run-vcpkg#68]
On my fork of a project, I hit this weird problem of being in an in-between state or something when it comes to caching:

https://github.com/TrueBrain/OpenTTD/runs/1668083380?check_suite_focus=true

When trying to restore the cache, it reads:
```
Restore vcpkg and its artifacts from cache
  Cache's key = 'localGitId=42-args=-2010035955-os=1553167195-appendedKey=42-triplet=877224823', paths = 'c:\vcpkg,!c:\vcpkg\packages,!c:\vcpkg\buildtrees,!c:\vcpkg\downloads'
  Running restore-cache...
  Cache miss.
```

When trying to store the cache, it reads:
```
   Caching paths: 'c:\vcpkg,!c:\vcpkg\packages,!c:\vcpkg\buildtrees,!c:\vcpkg\downloads'
  Running save-cache with key 'localGitId=42-args=-2010035955-os=1553167195-appendedKey=42-triplet=877224823' ...
  Warning: reserveCache failed: Cache already exists. Scope: refs/heads/master, Key: localGitId=42-args=-2010035955-os=1553167195-appendedKey=42-triplet=877224823, Version: e596d9224b0d5487c49893de7ad8700f61714e1ba95b948df70e6f4d9d37eb16
```

And I never end up with anything in the cache :) This only happens on my fork; the upstream project is doing just fine. Not sure what happened, or how to reproduce, honestly. I am just hoping you are like: owh, doh, of course, and that is is a simple fix on either of our ends :D

Tnx!

**Comment by lukka** [comment]
@TrueBrain i compared the key and the paths (the latter are part of the key as well), and they perfectly match in your workflow. There must be something wrong on the GitHub cache service, especially since this is working upstream.

By enabling on your fork repository the [verbose logging of the runners and of the steps](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/enabling-debug-logging) may shed some light.

I have fixed a similar problem in latest run-vcpkg release `v6.1`, and I see you are already using latest version indeed.

**Comment by TrueBrain** [comment]
Meh, honestly, that is not worth the effort. I was hoping there was something obvious I was doing wrong or could do, but as there is not, let's just leave it as this :) If you get more of these report it might be worth looking into, but I did a lot of crazy stuff in my fork, so yeah .. I am just going to assume I broke GitHub :D

Tnx for you time :)
