### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by cenit** [lukka/run-vcpkg#70]
Thank you very much for your fantastic actions and sorry for my inability to understand them fully.
We are trying to use them in the yolo/Darknet project (feel free to add them to real world examples if you want, after they will be fixed...).
Unfortunately I am experiencing no cache at all for vcpkg artifacts. May I ask you what am I doing wrong?

https://github.com/AlexeyAB/darknet/blob/master/.github/workflows/ccpp.yml

Thank you very very much for your time

**Comment by lukka** [comment]
@cenit I've got a brief look to the logs of the workflow, and it looks like that the problem is that `run-vcpkg` with `setupOnly:true` does not store anything in cache when the workflow fails. Same topic has been discussed here:
https://github.com/lukka/run-vcpkg/issues/58
Is this correct?

On the contrary, when `setupOnly:false`, the cache is stored at the end of the `run-vcpkg` step  execution (and not at the end of the workflow).

I still have to implement a solution that is letting the user to choose whether to store the cache always even when something failed in the workflow before reaching the post actions phase.

**Comment by lukka** [comment]
Let me know if there is otherwise anything that can be done on `run-vcpkg` side to address this problem

**Comment by cenit** [comment]
sorry for no reactions on your nice reply.
It was/is a very busy time for me on many other projects, but that problem was solved thanks also to a better script refactor. I am stuck with other strange behaviours related to CUDA and run-vcpkg, but that's another topic and I will open another issue in case of persisting problems.
Thanks again for your nice actions!
